<a href="https://colab.research.google.com/github/rahulgundre/SHALA2020/blob/master/Copy_of_Assignment_1_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **Assignment - 1 : Getting Started**

---

This assignment will get you familiarized with python libraries required for ***data science*** and ***machine learning***. You will have to complete the code snippets and run them. 

## **Note :**   Use only the methods and attributes of the ```numpy``` library. **Do not** hard-code them. Avoid loops as much as possible.

---
## Part - 1
 In this part, you will work with the library ```numpy```. 




Import ```numpy``` with an alias name ```np```. Initialize two arrays $a$, $b$ of size $3 \times 5$ with random values and print them. 

In [0]:
import numpy as np

In [53]:
a=np.random.rand(3,5)
print("a={}".format(a))
b=np.random.rand(3,5)
print("b={}".format(b))

a=[[0.1920723  0.72566962 0.7849367  0.97209836 0.85097142]
 [0.54359433 0.08979087 0.48887324 0.92793635 0.7876182 ]
 [0.48509423 0.45527936 0.21798577 0.17721338 0.07362367]]
b=[[0.89239319 0.64017662 0.14333232 0.41412692 0.04910892]
 [0.20937335 0.73070812 0.65112277 0.4789783  0.27478051]
 [0.65222313 0.95644951 0.43552056 0.07013251 0.05773149]]


Initialize and print two arrays $c$ and $d$ having the following properties:
*   $c$ is a row vector with all non-negative integer values less than 100
* $d$ is a square matrix of size 3 having all entries as 0.0

In [54]:
c=np.arange(0,100)
print("c={}".format(c))
print('-'*50)
d=np.zeros((3,3),dtype=float)
print("d={}".format(d))





c=[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
--------------------------------------------------
d=[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


We have $e$ as following : ```e = [[1,2,3],[4,5,6],[7,8,9]]```. Change $e$ as a numpy array and print it.

In [55]:
e = [[1,2,3],[4,5,6],[7,8,9]]
e=np.array(e)
print("e={}".format(e))

e=[[1 2 3]
 [4 5 6]
 [7 8 9]]


$f$ and $g$ are two square matrices of size 5 such that all the entries of $f$ are 1 and $g$ is an identity matrix. Initialize them and print them

In [56]:
f=np.ones((5,5))
print("f={}".format(f))
g=np.eye(5)
print("g={}".format(g))

f=[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
g=[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Reshape $c$ into a $10 \times 10$ matrix and name it $h$. Now flatten $h$, call it $c^\prime$ and print **YES** when the shapes of $c$ and $c^\prime$ are same. Otherwise print **NO**.

In [57]:
h=c.reshape((10,10))
c_dash=h.flatten()
if c.all()==c_dash.all():
  print("Yes")
else:
  print("No")

Yes


Let $A$ denote a randomly initialized three dimensional matrix of shape (2,10,5). Transpose $A$, call it $A^\prime$, such that its shape is (5,2,10) and print it.

In [58]:
A = np.random.rand(2,10,5)
print("A={}".format(A))
print("-"*50)
A_dash=A.transpose((2,0,1))
print("A_dash={}".format(A_dash))


A=[[[8.28710188e-02 9.59707187e-01 5.40760836e-01 8.37462433e-01
   1.70033544e-01]
  [2.60345073e-01 6.91977512e-01 8.95570328e-01 3.40688484e-01
   6.46731980e-02]
  [8.64119669e-01 2.90872446e-01 7.41082406e-01 1.58033655e-01
   6.94963435e-01]
  [8.41419619e-01 7.27152079e-01 3.59107525e-01 7.26689751e-01
   1.39467124e-01]
  [3.13819115e-01 4.19582757e-01 8.77212039e-01 1.53740209e-01
   8.80124790e-01]
  [7.98964319e-01 9.71624297e-01 3.67702983e-01 2.04939769e-01
   2.40570320e-01]
  [8.27862801e-01 9.65228149e-01 6.98809998e-01 4.82497042e-01
   2.87049765e-01]
  [8.33687884e-01 8.72179508e-01 9.21315918e-02 2.15949471e-01
   8.31761090e-01]
  [8.48303897e-01 3.14652999e-01 2.79294597e-01 4.30815022e-01
   5.39446500e-01]
  [9.55668150e-02 8.36912139e-01 5.34734870e-01 7.74967815e-01
   2.30836266e-01]]

 [[9.65293351e-01 7.51027307e-01 3.43093864e-01 9.48527647e-01
   7.00511779e-01]
  [8.40561085e-01 4.54973059e-02 5.56415411e-02 7.42737274e-01
   3.04686433e-01]
  [5.1678436

You have a matrix $X$ of size (10,5) filled with random values. Print the following :
* Minimum value and index where it occured, for each column
* Maximum value and the index where it occured, for each column
* Minimum value and index where it occured, for each row
* Maximum value and index where it occured, for each row
* Minimum value and index where it occured, for the entire matrix
* Maximum value and index where it occured, for the entire matrix

In [59]:
np.random.seed(0)
X = np.random.rand(10,5)
print("X={}".format(X))
min_col=np.min(X,axis=0)
print("min_col={}".format(min_col))
min_ind_col=np.argmin(X,axis=0)
print("min_index_col={}".format(min_ind_col))
print("-"*50)
max_col=np.max(X,axis=0)
print("max_col={}".format(max_col))
max_ind_col=np.argmin(X,axis=0)
print("max_index_col={}".format(max_ind_col))
print("-"*100)
min_row=np.max(X,axis=0)
print("min_row={}".format(min_row))
min_ind_row=np.argmin(X,axis=1)
print("min_index_row={}".format(min_ind_row))
print("-"*50)
max_row=np.max(X,axis=1)
print("max_row={}".format(max_row))
max_ind_row=np.argmax(X,axis=1)
print("max_index_row={}".format(max_ind_row))
print("-"*100)
print("min(X) = {}".format(np.min(X),axis=0))
print("argmin(X) = {}".format(np.argmin(X),axis=0))
print("-"*100)
print("max(X) = {}".format(np.max(X),axis=0))
print("argmax(X) = {}".format(np.argmax(X),axis=0))

X=[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
 [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918 0.11827443]
 [0.63992102 0.14335329 0.94466892 0.52184832 0.41466194]
 [0.26455561 0.77423369 0.45615033 0.56843395 0.0187898 ]
 [0.6176355  0.61209572 0.616934   0.94374808 0.6818203 ]
 [0.3595079  0.43703195 0.6976312  0.06022547 0.66676672]
 [0.67063787 0.21038256 0.1289263  0.31542835 0.36371077]]
min_col=[0.0871293  0.0202184  0.1289263  0.06022547 0.0187898 ]
min_index_col=[3 3 9 8 6]
--------------------------------------------------
max_col=[0.97861834 0.79915856 0.94466892 0.96366276 0.87001215]
max_index_col=[3 3 9 8 6]
----------------------------------------------------------------------------------------------------
min_row=[0.97861834 0.79915856 0.94466892 0.96366276 0.87001215]
min_index_row=[4 4

Find and print the following for the matrix X: 
* Mean of each row and column
* Standard deviation of each row and column
* Mean of the entire matrix
* Standard deviation of entire matrix

In [60]:
print(X)
print("-"*100)
print("Mean along rows:\n",np.mean(X,axis=1))
print('mean along columns:\n',np.mean(X,axis=0))
print("Standard deviation along rows:\n",np.std(X,axis=1))
print('Standard deviation along columns:\n',np.std(X,axis=0))
print("Overall mean is:", X.mean())
print("Std is:",X.std())

[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
 [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918 0.11827443]
 [0.63992102 0.14335329 0.94466892 0.52184832 0.41466194]
 [0.26455561 0.77423369 0.45615033 0.56843395 0.0187898 ]
 [0.6176355  0.61209572 0.616934   0.94374808 0.6818203 ]
 [0.3595079  0.43703195 0.6976312  0.06022547 0.66676672]
 [0.67063787 0.21038256 0.1289263  0.31542835 0.36371077]]
----------------------------------------------------------------------------------------------------
Mean along rows:
 [0.56706085 0.66447172 0.57705944 0.51762729 0.62761197 0.5328907
 0.41643268 0.69444672 0.44423265 0.33781717]
mean along columns:
 [0.56044382 0.46781457 0.62009909 0.64025127 0.40121685]
Standard deviation along rows:
 [0.09445299 0.23322986 0.29189733 0.38052993 0.30431633 0.26338419
 0.25841437

Let $Y$ denote a square matrix of size 10 with random values. Print the following:
* Determinant
* Rank of the matrix
* Diagonal Elements
* Trace
* Eigen values
* Matrices obtained after Singular Value Decomposition
* Inverse if exists, otherwise Pseudo-Inverse
* Multiplication $Y$ with $X$
* Element-wise multiplication of $Y$ and its inverse(or pseudo-inverse)

In [66]:
np.random.seed(3)
Y = np.random.rand(10,10)
print(Y)
det=np.linalg.det(Y)
print('determinant is:{}'.format(det))
rank=np.linalg.matrix_rank(Y)
print('Rank is {}'.format(rank))
print("trace is :",Y.trace())
eig_val, eig_vec = np.linalg.eig(Y)
print("Eigen values are:\n".format(eig_val))
print("Eigen vectors are:\n".format(eig_vec))
u,s,vh=np.linalg.svd(Y)
u
print("U of Y is\n".format(u))
print("V of Y is:\n".format(vh))
print("Singular values of Y are:\n".format(s))
Inverse=np.linalg.pinv(Y)
print('Inverse is:'.format(Inverse))
# z=np.dot(X,Y)
# print('Element multiplication:{}'.format(z))
# I=np.matmul(Y,Inverse)
# print('matrix multi:{}'.format(I))

[[0.5507979  0.70814782 0.29090474 0.51082761 0.89294695 0.89629309
  0.12558531 0.20724288 0.0514672  0.44080984]
 [0.02987621 0.45683322 0.64914405 0.27848728 0.6762549  0.59086282
  0.02398188 0.55885409 0.25925245 0.4151012 ]
 [0.28352508 0.69313792 0.44045372 0.15686774 0.54464902 0.78031476
  0.30636353 0.22195788 0.38797126 0.93638365]
 [0.97599542 0.67238368 0.90283411 0.84575087 0.37799404 0.09221701
  0.6534109  0.55784076 0.36156476 0.2250545 ]
 [0.40651992 0.46894025 0.26923558 0.29179277 0.4576864  0.86053391
  0.5862529  0.28348786 0.27797751 0.45462208]
 [0.20541034 0.20137871 0.51403506 0.08722937 0.48358553 0.36217621
  0.70768662 0.74674622 0.69109292 0.68918041]
 [0.37360012 0.6681348  0.33984866 0.57279387 0.32580716 0.44514505
  0.06152893 0.24267542 0.97160261 0.2305842 ]
 [0.69147751 0.65047686 0.72393914 0.47508861 0.59666377 0.06696942
  0.07256214 0.19897603 0.151861   0.10010434]
 [0.12929386 0.55327773 0.18781482 0.95210124 0.68161178 0.54101967
  0.7071806 

In [0]:
from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode

def take_photo(filename='photo.jpg', quality=0.8):
  js = Javascript('''
    async function takePhoto(quality) {
      const div = document.createElement('div');
      const capture = document.createElement('button');
      capture.textContent = 'Capture';
      div.appendChild(capture);

      const video = document.createElement('video');
      video.style.display = 'block';
      const stream = await navigator.mediaDevices.getUserMedia({video: true});

      document.body.appendChild(div);
      div.appendChild(video);
      video.srcObject = stream;
      await video.play();

      // Resize the output to fit the video element.
      google.colab.output.setIframeHeight(document.documentElement.scrollHeight, true);

      // Wait for Capture to be clicked.
      await new Promise((resolve) => capture.onclick = resolve);

      const canvas = document.createElement('canvas');
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      canvas.getContext('2d').drawImage(video, 0, 0);
      stream.getVideoTracks()[0].stop();
      div.remove();
      return canvas.toDataURL('image/jpeg', quality);
    }
    ''')
  display(js)
  data = eval_js('takePhoto({})'.format(quality))
  binary = b64decode(data.split(',')[1])
  with open(filename, 'wb') as f:
    f.write(binary)
  return filename

In [0]:
from IPython.display import Image
try:
  filename = take_photo()
  print('Saved to {}'.format(filename))
  
  # Show the image which was just taken.
  display(Image(filename))
except Exception as err:
  # Errors will be thrown if the user does not have a webcam or if they do not
  # grant the page permission to access it.
  print(str(err))

## End of Part - 1
 --- --- ---

## Part - 2
---
In this part, you will be working with the library ```pandas```. Import this library with an alias name ```pd```.

In [0]:
# Initial imports
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv
Read the data and display the first 5 rows

In [80]:
!pip install url

In [73]:
#Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv
from urllib.request import urlretrieve
file_url = "http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv"
urlretrieve(file_url,"titanic3.csv")




('titanic3.csv', <http.client.HTTPMessage at 0x7feeaab08c18>)

In [0]:
titanic=pd.read_csv("titanic3.csv")

In [79]:
titanic.head()

pclass  survived  ...   body                        home.dest
0       1         1  ...    NaN                     St Louis, MO
1       1         1  ...    NaN  Montreal, PQ / Chesterville, ON
2       1         0  ...    NaN  Montreal, PQ / Chesterville, ON
3       1         0  ...  135.0  Montreal, PQ / Chesterville, ON
4       1         0  ...    NaN  Montreal, PQ / Chesterville, ON

[5 rows x 14 columns]

### Preprocessing of the Dataset



---


**1. Convert the categorical values of columns 'sex', 'embarked', 'pclass' into dummy values and add them into titanic_data_new DataFrame**




---





---


**2. Fill the missing data in Age and Fare columns with the mean value of the respected column then add these columns to titanic_data_new**


---



###Normalization


---



1. Normalize the columns which have numerical data



---





---
2. Drop the original age, fare columns
3. Append the normalized columns to the titanic_data_new DataFrame.



---



###Plotting
1. plot the age against the ID(continuous)
2. plot the fare against the ID(scatter)

## End of Part - 2
---

## Part - 3
---

In this part, you will work with the library ```matplotlib```. Import the ```pyplot``` from ```matplotlib``` with an alias name ```plt```.

Plot the sine function with domain in $[-3\pi,3\pi]$. Label the axes appropriately. Add title $\sin(x)$. Use latex formatting while adding the title. Set the plot size to (10,10)

Plot $\sin(x)$ and its spectrum, $\cos(x)$ and its spectrum in a single plot, in the domain $[-2\pi,2\pi]$. Label the plot appropriately.

## End of Part - 3
---

Create a Github repository with the name ***SHALA2020*** and save this assignment there.